In [49]:
print("reck98")
!(which python)
!(python --version)

reck98
/run/media/reck98/Others/Development/ML_NLP_DL/dl/.venv/bin/python
Python 3.12.12

In [50]:
import torch

print("PyTorch:", torch.__version__)
print("CUDA Available:", torch.cuda.is_available())
print("CUDA Version:", torch.version.cuda)
print("GPU:", torch.cuda.get_device_name(0))

PyTorch: 2.6.0+cu124
CUDA Available: True
CUDA Version: 12.4
GPU: NVIDIA GeForce RTX 2050

In [51]:
print(torch.__version__)

2.6.0+cu124

In [52]:
x = torch.tensor([1, 2, 3])

In [53]:
print(type(x))

<class 'torch.Tensor'>

In [54]:
r = torch.rand(2, 3)

In [55]:
r

tensor([[0.9157, 0.2114, 0.0658],
        [0.7076, 0.3364, 0.1434]])

In [56]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn


from sklearn.model_selection import train_test_split

In [57]:
## ANN model

## data 

df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],

    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],

    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],

    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})


df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [58]:
X = df.drop("needs_water", axis=1)
y = df["needs_water"]

In [59]:
X_min = X.min()
X_max = X.max()

X = (X - X_min) / ( X_max - X_min + 1e-8)

In [60]:
X

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [61]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)

In [62]:
import torch
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(3, 1),
    nn.Sigmoid(),
)

criterion = nn.BCELoss()

optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# Convert pandas dataframe -> tensor
X_train = torch.tensor(X_train.to_numpy(), dtype=torch.float32)
X_test = torch.tensor(X_test.to_numpy(), dtype=torch.float32)

# Convert pandas series -> tensor
y_train = torch.tensor(y_train.to_numpy(), dtype=torch.float32).view(-1, 1)
y_test = torch.tensor(y_test.to_numpy(), dtype=torch.float32).view(-1, 1)

# epochs = 10000000

In [63]:
print(torch.cuda.is_available())

True

In [64]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

model = model.to(device)

X_train = X_train.to(device)
X_test = X_test.to(device)

y_train = y_train.to(device)
y_test = y_test.to(device)

In [65]:
epochs_used = 0

while(1):

    # Forward pass
    y_pred = model(X_train)

    # Loss
    loss = criterion(y_pred, y_train)

    # Backpropagation
    optimizer.zero_grad()

    loss.backward()

    optimizer.step()
    
    if (epochs_used % 10000 == 0):
        print(f"Epoch: {epochs_used}, Loss: {loss.item()}")
    
    epochs_used += 1
    
    if (loss.item() < 0.01):
        break
    
print(f"Total Epochs used: {epochs_used}")

Epoch: 0, Loss: 0.7233230471611023
Epoch: 10000, Loss: 0.32276052236557007
Epoch: 20000, Loss: 0.24886195361614227
Epoch: 30000, Loss: 0.21090279519557953
Epoch: 40000, Loss: 0.18615767359733582
Epoch: 50000, Loss: 0.16826170682907104
Epoch: 60000, Loss: 0.15451136231422424
Epoch: 70000, Loss: 0.1435091197490692
Epoch: 80000, Loss: 0.1344437599182129
Epoch: 90000, Loss: 0.12680332362651825
Epoch: 100000, Loss: 0.12024906277656555
Epoch: 110000, Loss: 0.11454425752162933
Epoch: 120000, Loss: 0.10952075570821762
Epoch: 130000, Loss: 0.10504445433616638
Epoch: 140000, Loss: 0.10102997720241547
Epoch: 150000, Loss: 0.09739898145198822
Epoch: 160000, Loss: 0.09409546852111816
Epoch: 170000, Loss: 0.09106766432523727
Epoch: 180000, Loss: 0.08828141540288925
Epoch: 190000, Loss: 0.08570688217878342
Epoch: 200000, Loss: 0.08332210034132004
Epoch: 210000, Loss: 0.08109143376350403
Epoch: 220000, Loss: 0.07900015264749527
Epoch: 230000, Loss: 0.0770556852221489
Epoch: 240000, Loss: 0.07522859424352646
Epoch: 250000, Loss: 0.07348140329122543
Epoch: 260000, Loss: 0.07186523079872131
Epoch: 270000, Loss: 0.07030271738767624
Epoch: 280000, Loss: 0.06885179132223129
Epoch: 290000, Loss: 0.0674445629119873
Epoch: 300000, Loss: 0.06613045930862427
Epoch: 310000, Loss: 0.06485509127378464
Epoch: 320000, Loss: 0.0636594146490097
Epoch: 330000, Loss: 0.06250454485416412
Epoch: 340000, Loss: 0.06137564778327942
Epoch: 350000, Loss: 0.06033286452293396
Epoch: 360000, Loss: 0.059316471219062805
Epoch: 370000, Loss: 0.05832049995660782
Epoch: 380000, Loss: 0.057384781539440155
Epoch: 390000, Loss: 0.056489162147045135
Epoch: 400000, Loss: 0.05561148375272751
Epoch: 410000, Loss: 0.054754793643951416
Epoch: 420000, Loss: 0.05395708233118057
Epoch: 430000, Loss: 0.05317540094256401
Epoch: 440000, Loss: 0.05241077393293381
Epoch: 450000, Loss: 0.05166330188512802
Epoch: 460000, Loss: 0.05096191167831421
Epoch: 470000, Loss: 0.05028299614787102
Epoch: 480000, Loss: 0.04961438104510307
Epoch: 490000, Loss: 0.04895613715052605
Epoch: 500000, Loss: 0.048310376703739166
Epoch: 510000, Loss: 0.04769762605428696
Epoch: 520000, Loss: 0.04711967706680298
Epoch: 530000, Loss: 0.04654990881681442
Epoch: 540000, Loss: 0.04598790407180786
Epoch: 550000, Loss: 0.045471519231796265
Epoch: 560000, Loss: 0.04496806114912033
Epoch: 570000, Loss: 0.044474340975284576
Epoch: 580000, Loss: 0.04398765414953232
Epoch: 590000, Loss: 0.04350697249174118
Epoch: 600000, Loss: 0.04303246736526489
Epoch: 610000, Loss: 0.04256373271346092
Epoch: 620000, Loss: 0.042100690305233
Epoch: 630000, Loss: 0.04164335876703262
Epoch: 640000, Loss: 0.04119178280234337
Epoch: 650000, Loss: 0.0407455675303936
Epoch: 660000, Loss: 0.04030468314886093
Epoch: 670000, Loss: 0.0398690402507782
Epoch: 680000, Loss: 0.03943859040737152
Epoch: 690000, Loss: 0.03901505097746849
Epoch: 700000, Loss: 0.0386335514485836
Epoch: 710000, Loss: 0.038288362324237823
Epoch: 720000, Loss: 0.037948839366436005
Epoch: 730000, Loss: 0.03761248290538788
Epoch: 740000, Loss: 0.03727937489748001
Epoch: 750000, Loss: 0.03694940358400345
Epoch: 760000, Loss: 0.03662391006946564
Epoch: 770000, Loss: 0.036303456872701645
Epoch: 780000, Loss: 0.03598664700984955
Epoch: 790000, Loss: 0.0356733500957489
Epoch: 800000, Loss: 0.03536427021026611
Epoch: 810000, Loss: 0.03505994379520416
Epoch: 820000, Loss: 0.03475912660360336
Epoch: 830000, Loss: 0.03446138650178909
Epoch: 840000, Loss: 0.034166451543569565
Epoch: 850000, Loss: 0.03387424349784851
Epoch: 860000, Loss: 0.03358475863933563
Epoch: 870000, Loss: 0.03329835087060928
Epoch: 880000, Loss: 0.033014584332704544
Epoch: 890000, Loss: 0.03273338824510574
Epoch: 900000, Loss: 0.03245481476187706
Epoch: 910000, Loss: 0.032178714871406555
Epoch: 920000, Loss: 0.031905170530080795
Epoch: 930000, Loss: 0.03163410723209381
Epoch: 940000, Loss: 0.031365491449832916
Epoch: 950000, Loss: 0.03109969198703766
Epoch: 960000, Loss: 0.030848652124404907
Epoch: 970000, Loss: 0.03061363846063614
Epoch: 980000, Loss: 0.03040042147040367
Epoch: 990000, Loss: 0.03019925020635128
Epoch: 1000000, Loss: 0.029999515041708946
Epoch: 1010000, Loss: 0.02980114333331585
Epoch: 1020000, Loss: 0.029604267328977585
Epoch: 1030000, Loss: 0.029410406947135925
Epoch: 1040000, Loss: 0.02921963296830654
Epoch: 1050000, Loss: 0.029030172154307365
Epoch: 1060000, Loss: 0.028842009603977203
Epoch: 1070000, Loss: 0.02865515649318695
Epoch: 1080000, Loss: 0.028471127152442932
Epoch: 1090000, Loss: 0.028288861736655235
Epoch: 1100000, Loss: 0.028107812628149986
Epoch: 1110000, Loss: 0.027927987277507782
Epoch: 1120000, Loss: 0.02774950861930847
Epoch: 1130000, Loss: 0.027573570609092712
Epoch: 1140000, Loss: 0.027398845180869102
Epoch: 1150000, Loss: 0.027225276455283165
Epoch: 1160000, Loss: 0.027052855119109154
Epoch: 1170000, Loss: 0.026881616562604904
Epoch: 1180000, Loss: 0.026711512356996536
Epoch: 1190000, Loss: 0.026542505249381065
Epoch: 1200000, Loss: 0.026374638080596924
Epoch: 1210000, Loss: 0.026207953691482544
Epoch: 1220000, Loss: 0.026042602956295013
Epoch: 1230000, Loss: 0.025878366082906723
Epoch: 1240000, Loss: 0.025715183466672897
Epoch: 1250000, Loss: 0.02555309236049652
Epoch: 1260000, Loss: 0.025392061099410057
Epoch: 1270000, Loss: 0.02523208223283291
Epoch: 1280000, Loss: 0.025073189288377762
Epoch: 1290000, Loss: 0.024915333837270737
Epoch: 1300000, Loss: 0.02475876733660698
Epoch: 1310000, Loss: 0.024603180587291718
Epoch: 1320000, Loss: 0.02444859966635704
Epoch: 1330000, Loss: 0.024295028299093246
Epoch: 1340000, Loss: 0.0241424348205328
Epoch: 1350000, Loss: 0.023990720510482788
Epoch: 1360000, Loss: 0.023839978501200676
Epoch: 1370000, Loss: 0.023690257221460342
Epoch: 1380000, Loss: 0.02354147844016552
Epoch: 1390000, Loss: 0.023393690586090088
Epoch: 1400000, Loss: 0.0232468843460083
Epoch: 1410000, Loss: 0.023100998252630234
Epoch: 1420000, Loss: 0.022956103086471558
Epoch: 1430000, Loss: 0.022819196805357933
Epoch: 1440000, Loss: 0.022683236747980118
Epoch: 1450000, Loss: 0.022550929337739944
Epoch: 1460000, Loss: 0.022429227828979492
Epoch: 1470000, Loss: 0.022312715649604797
Epoch: 1480000, Loss: 0.022198479622602463
Epoch: 1490000, Loss: 0.022096484899520874
Epoch: 1500000, Loss: 0.021996255964040756
Epoch: 1510000, Loss: 0.02189650759100914
Epoch: 1520000, Loss: 0.02179722860455513
Epoch: 1530000, Loss: 0.021698396652936935
Epoch: 1540000, Loss: 0.021600943058729172
Epoch: 1550000, Loss: 0.021504171192646027
Epoch: 1560000, Loss: 0.02140929363667965
Epoch: 1570000, Loss: 0.02131502889096737
Epoch: 1580000, Loss: 0.021221203729510307
Epoch: 1590000, Loss: 0.02112778276205063
Epoch: 1600000, Loss: 0.021034810692071915
Epoch: 1610000, Loss: 0.020942246541380882
Epoch: 1620000, Loss: 0.02085009589791298
Epoch: 1630000, Loss: 0.020758386701345444
Epoch: 1640000, Loss: 0.020667720586061478
Epoch: 1650000, Loss: 0.0205784123390913
Epoch: 1660000, Loss: 0.020489536225795746
Epoch: 1670000, Loss: 0.02040105313062668
Epoch: 1680000, Loss: 0.020312940701842308
Epoch: 1690000, Loss: 0.020225228741765022
Epoch: 1700000, Loss: 0.020137939602136612
Epoch: 1710000, Loss: 0.020051000639796257
Epoch: 1720000, Loss: 0.019964491948485374
Epoch: 1730000, Loss: 0.01987903192639351
Epoch: 1740000, Loss: 0.01979478821158409
Epoch: 1750000, Loss: 0.01971093937754631
Epoch: 1760000, Loss: 0.019627491012215614
Epoch: 1770000, Loss: 0.019544344395399094
Epoch: 1780000, Loss: 0.019461601972579956
Epoch: 1790000, Loss: 0.01937924325466156
Epoch: 1800000, Loss: 0.01929718255996704
Epoch: 1810000, Loss: 0.019215522333979607
Epoch: 1820000, Loss: 0.019134236499667168
Epoch: 1830000, Loss: 0.019054370000958443
Epoch: 1840000, Loss: 0.018974900245666504
Epoch: 1850000, Loss: 0.018895741552114487
Epoch: 1860000, Loss: 0.018816933035850525
Epoch: 1870000, Loss: 0.01873846910893917
Epoch: 1880000, Loss: 0.018660318106412888
Epoch: 1890000, Loss: 0.01858251541852951
Epoch: 1900000, Loss: 0.01850508339703083
Epoch: 1910000, Loss: 0.018427927047014236
Epoch: 1920000, Loss: 0.018351107835769653
Epoch: 1930000, Loss: 0.018274664878845215
Epoch: 1940000, Loss: 0.018198490142822266
Epoch: 1950000, Loss: 0.01812267117202282
Epoch: 1960000, Loss: 0.018047183752059937
Epoch: 1970000, Loss: 0.017972007393836975
Epoch: 1980000, Loss: 0.017897125333547592
Epoch: 1990000, Loss: 0.017822623252868652
Epoch: 2000000, Loss: 0.017748381942510605
Epoch: 2010000, Loss: 0.017674488946795464
Epoch: 2020000, Loss: 0.01760104112327099
Epoch: 2030000, Loss: 0.01752788946032524
Epoch: 2040000, Loss: 0.017455032095313072
Epoch: 2050000, Loss: 0.017382510006427765
Epoch: 2060000, Loss: 0.01731029897928238
Epoch: 2070000, Loss: 0.017238348722457886
Epoch: 2080000, Loss: 0.017166776582598686
Epoch: 2090000, Loss: 0.017095454037189484
Epoch: 2100000, Loss: 0.017024438828229904
Epoch: 2110000, Loss: 0.016953734681010246
Epoch: 2120000, Loss: 0.01688334159553051
Epoch: 2130000, Loss: 0.016813231632113457
Epoch: 2140000, Loss: 0.016743451356887817
Epoch: 2150000, Loss: 0.016673948615789413
Epoch: 2160000, Loss: 0.016604704782366753
Epoch: 2170000, Loss: 0.016535814851522446
Epoch: 2180000, Loss: 0.01646716520190239
Epoch: 2190000, Loss: 0.016398843377828598
Epoch: 2200000, Loss: 0.016330799087882042
Epoch: 2210000, Loss: 0.016263045370578766
Epoch: 2220000, Loss: 0.016195571050047874
Epoch: 2230000, Loss: 0.016128409653902054
Epoch: 2240000, Loss: 0.016061490401625633
Epoch: 2250000, Loss: 0.015994874760508537
Epoch: 2260000, Loss: 0.015928566455841064
Epoch: 2270000, Loss: 0.01586250588297844
Epoch: 2280000, Loss: 0.015796726569533348
Epoch: 2290000, Loss: 0.015731237828731537
Epoch: 2300000, Loss: 0.015666011720895767
Epoch: 2310000, Loss: 0.015600922517478466
Epoch: 2320000, Loss: 0.015536170452833176
Epoch: 2330000, Loss: 0.015471642836928368
Epoch: 2340000, Loss: 0.015407404862344265
Epoch: 2350000, Loss: 0.015343433246016502
Epoch: 2360000, Loss: 0.015279753133654594
Epoch: 2370000, Loss: 0.015216328203678131
Epoch: 2380000, Loss: 0.015153175219893456
Epoch: 2390000, Loss: 0.015090284869074821
Epoch: 2400000, Loss: 0.015027645044028759
Epoch: 2410000, Loss: 0.014965301379561424
Epoch: 2420000, Loss: 0.014903290197253227
Epoch: 2430000, Loss: 0.014841548167169094
Epoch: 2440000, Loss: 0.014780109748244286
Epoch: 2450000, Loss: 0.014718885533511639
Epoch: 2460000, Loss: 0.01465792115777731
Epoch: 2470000, Loss: 0.01459727343171835
Epoch: 2480000, Loss: 0.014536825940012932
Epoch: 2490000, Loss: 0.01447661779820919
Epoch: 2500000, Loss: 0.014416719786822796
Epoch: 2510000, Loss: 0.014357030391693115
Epoch: 2520000, Loss: 0.014297589659690857
Epoch: 2530000, Loss: 0.014238434843719006
Epoch: 2540000, Loss: 0.014183073304593563
Epoch: 2550000, Loss: 0.014129577204585075
Epoch: 2560000, Loss: 0.014076253399252892
Epoch: 2570000, Loss: 0.014023169875144958
Epoch: 2580000, Loss: 0.013970283791422844
Epoch: 2590000, Loss: 0.013917647302150726
Epoch: 2600000, Loss: 0.013865183107554913
Epoch: 2610000, Loss: 0.013812916353344917
Epoch: 2620000, Loss: 0.013760872185230255
Epoch: 2630000, Loss: 0.013709023594856262
Epoch: 2640000, Loss: 0.013658322393894196
Epoch: 2650000, Loss: 0.013611093163490295
Epoch: 2660000, Loss: 0.013570467941462994
Epoch: 2670000, Loss: 0.013530395925045013
Epoch: 2680000, Loss: 0.013490489684045315
Epoch: 2690000, Loss: 0.01345777790993452
Epoch: 2700000, Loss: 0.013425702229142189
Epoch: 2710000, Loss: 0.013393676839768887
Epoch: 2720000, Loss: 0.013361750170588493
Epoch: 2730000, Loss: 0.013329897075891495
Epoch: 2740000, Loss: 0.013298104517161846
Epoch: 2750000, Loss: 0.013266390189528465
Epoch: 2760000, Loss: 0.013234779238700867
Epoch: 2770000, Loss: 0.013203195296227932
Epoch: 2780000, Loss: 0.013171735219657421
Epoch: 2790000, Loss: 0.01314033567905426
Epoch: 2800000, Loss: 0.013108985498547554
Epoch: 2810000, Loss: 0.013077745214104652
Epoch: 2820000, Loss: 0.013046585023403168
Epoch: 2830000, Loss: 0.01301544439047575
Epoch: 2840000, Loss: 0.012984449975192547
Epoch: 2850000, Loss: 0.012953485362231731
Epoch: 2860000, Loss: 0.012923690490424633
Epoch: 2870000, Loss: 0.012894943356513977
Epoch: 2880000, Loss: 0.012866264209151268
Epoch: 2890000, Loss: 0.012837640009820461
Epoch: 2900000, Loss: 0.012809093110263348
Epoch: 2910000, Loss: 0.012780589982867241
Epoch: 2920000, Loss: 0.012752143666148186
Epoch: 2930000, Loss: 0.012723792344331741
Epoch: 2940000, Loss: 0.01269550807774067
Epoch: 2950000, Loss: 0.012667271308600903
Epoch: 2960000, Loss: 0.012639093212783337
Epoch: 2970000, Loss: 0.012611004523932934
Epoch: 2980000, Loss: 0.012582937255501747
Epoch: 2990000, Loss: 0.012554971501231194
Epoch: 3000000, Loss: 0.012527067214250565
Epoch: 3010000, Loss: 0.012499198317527771
Epoch: 3020000, Loss: 0.012471407651901245
Epoch: 3030000, Loss: 0.012443697080016136
Epoch: 3040000, Loss: 0.012416006997227669
Epoch: 3050000, Loss: 0.012388421222567558
Epoch: 3060000, Loss: 0.012360893189907074
Epoch: 3070000, Loss: 0.012333407998085022
Epoch: 3080000, Loss: 0.01230598520487547
Epoch: 3090000, Loss: 0.01227865181863308
Epoch: 3100000, Loss: 0.012251351028680801
Epoch: 3110000, Loss: 0.01222413033246994
Epoch: 3120000, Loss: 0.012196972034871578
Epoch: 3130000, Loss: 0.01216985285282135
Epoch: 3140000, Loss: 0.012142802588641644
Epoch: 3150000, Loss: 0.012115836143493652
Epoch: 3160000, Loss: 0.012088902294635773
Epoch: 3170000, Loss: 0.012062042020261288
Epoch: 3180000, Loss: 0.012035263702273369
Epoch: 3190000, Loss: 0.012008516117930412
Epoch: 3200000, Loss: 0.011981846764683723
Epoch: 3210000, Loss: 0.011955219320952892
Epoch: 3220000, Loss: 0.011928647756576538
Epoch: 3230000, Loss: 0.011902171187102795
Epoch: 3240000, Loss: 0.011875741183757782
Epoch: 3250000, Loss: 0.011849349364638329
Epoch: 3260000, Loss: 0.011823028326034546
Epoch: 3270000, Loss: 0.011796785518527031
Epoch: 3280000, Loss: 0.011770561337471008
Epoch: 3290000, Loss: 0.011744437739253044
Epoch: 3300000, Loss: 0.011718369089066982
Epoch: 3310000, Loss: 0.011692340485751629
Epoch: 3320000, Loss: 0.01166637521237135
Epoch: 3330000, Loss: 0.011640479788184166
Epoch: 3340000, Loss: 0.011614627204835415
Epoch: 3350000, Loss: 0.01158885657787323
Epoch: 3360000, Loss: 0.011563125066459179
Epoch: 3370000, Loss: 0.011537445709109306
Epoch: 3380000, Loss: 0.011511842720210552
Epoch: 3390000, Loss: 0.011486304923892021
Epoch: 3400000, Loss: 0.011460816487669945
Epoch: 3410000, Loss: 0.01143707986921072
Epoch: 3420000, Loss: 0.011413397267460823
Epoch: 3430000, Loss: 0.011389735154807568
Epoch: 3440000, Loss: 0.011366154067218304
Epoch: 3450000, Loss: 0.011342620477080345
Epoch: 3460000, Loss: 0.011319111101329327
Epoch: 3470000, Loss: 0.011295679025352001
Epoch: 3480000, Loss: 0.011272288858890533
Epoch: 3490000, Loss: 0.011248938739299774
Epoch: 3500000, Loss: 0.011225651018321514
Epoch: 3510000, Loss: 0.011202408000826836
Epoch: 3520000, Loss: 0.011179211549460888
Epoch: 3530000, Loss: 0.011156054213643074
Epoch: 3540000, Loss: 0.011132953688502312
Epoch: 3550000, Loss: 0.011109884828329086
Epoch: 3560000, Loss: 0.011086895130574703
Epoch: 3570000, Loss: 0.01106394361704588
Epoch: 3580000, Loss: 0.01104101724922657
Epoch: 3590000, Loss: 0.011018157005310059
Epoch: 3600000, Loss: 0.01099536381661892
Epoch: 3610000, Loss: 0.010972580872476101
Epoch: 3620000, Loss: 0.010949875228106976
Epoch: 3630000, Loss: 0.010927191935479641
Epoch: 3640000, Loss: 0.010904569178819656
Epoch: 3650000, Loss: 0.010881982743740082
Epoch: 3660000, Loss: 0.010859480127692223
Epoch: 3670000, Loss: 0.010836987756192684
Epoch: 3680000, Loss: 0.010814560577273369
Epoch: 3690000, Loss: 0.01079217903316021
Epoch: 3700000, Loss: 0.010769831947982311
Epoch: 3710000, Loss: 0.010747547261416912
Epoch: 3720000, Loss: 0.010725314728915691
Epoch: 3730000, Loss: 0.010703084990382195
Epoch: 3740000, Loss: 0.010680949315428734
Epoch: 3750000, Loss: 0.010658849030733109
Epoch: 3760000, Loss: 0.010636764578521252
Epoch: 3770000, Loss: 0.010614755563437939
Epoch: 3780000, Loss: 0.010592803359031677
Epoch: 3790000, Loss: 0.010570861399173737
Epoch: 3800000, Loss: 0.010548995807766914
Epoch: 3810000, Loss: 0.010527156293392181
Epoch: 3820000, Loss: 0.010505381040275097
Epoch: 3830000, Loss: 0.010483636520802975
Epoch: 3840000, Loss: 0.010461946949362755
Epoch: 3850000, Loss: 0.010440278798341751
Epoch: 3860000, Loss: 0.010418678633868694
Epoch: 3870000, Loss: 0.010397115722298622
Epoch: 3880000, Loss: 0.010375604033470154
Epoch: 3890000, Loss: 0.010354150086641312
Epoch: 3900000, Loss: 0.010332721285521984
Epoch: 3910000, Loss: 0.010311330668628216
Epoch: 3920000, Loss: 0.010290000587701797
Epoch: 3930000, Loss: 0.010268726386129856
Epoch: 3940000, Loss: 0.010247460566461086
Epoch: 3950000, Loss: 0.010226268321275711
Epoch: 3960000, Loss: 0.010205130092799664
Epoch: 3970000, Loss: 0.010183986276388168
Epoch: 3980000, Loss: 0.010162933729588985
Epoch: 3990000, Loss: 0.010141895152628422
Epoch: 4000000, Loss: 0.01012091152369976
Epoch: 4010000, Loss: 0.010099982842803001
Epoch: 4020000, Loss: 0.010079088620841503
Epoch: 4030000, Loss: 0.010058222338557243
Epoch: 4040000, Loss: 0.010037441737949848
Epoch: 4050000, Loss: 0.010016675107181072
Total Epochs used: 4058049

In [67]:
with torch.no_grad():

    # Predictions
    y_pred = model(X_test)

    # Convert probabilities to 0 or 1
    predicted = (y_pred >= 0.5).float()

    # Accuracy
    accuracy = (predicted == y_test).float().mean()

    print(f"Accuracy: {accuracy.item() * 100:.2f}%")

Accuracy: 75.00%

In [77]:
epochs_used = 1_000_000

for epoch in range(epochs_used):

    # Forward pass
    y_pred = model(X_train)

    # Loss
    loss = criterion(y_pred, y_train)

    # Backpropagation
    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    print(f"Epoch: {epoch}, Loss: {loss.item()}")

print(f"Total Epochs used: {epoch + 1}")

Epoch: 0, Loss: 0.009999768808484077
Epoch: 1, Loss: 0.00999978743493557
Epoch: 2, Loss: 0.009999769739806652
Epoch: 3, Loss: 0.009999768808484077
Epoch: 4, Loss: 0.00999976322054863
Epoch: 5, Loss: 0.009999765083193779
Epoch: 6, Loss: 0.009999774396419525
Epoch: 7, Loss: 0.009999766945838928
Epoch: 8, Loss: 0.009999753907322884
Epoch: 9, Loss: 0.009999765083193779
Epoch: 10, Loss: 0.009999750182032585
Epoch: 11, Loss: 0.009999748319387436
Epoch: 12, Loss: 0.009999752044677734
Epoch: 13, Loss: 0.009999759495258331
Epoch: 14, Loss: 0.009999744594097137
Epoch: 15, Loss: 0.009999728761613369
Epoch: 16, Loss: 0.009999747388064861
Epoch: 17, Loss: 0.009999731555581093
Epoch: 18, Loss: 0.00999975111335516
Epoch: 19, Loss: 0.009999734349548817
Epoch: 20, Loss: 0.009999718517065048
Epoch: 21, Loss: 0.009999732486903667
Epoch: 22, Loss: 0.009999718517065048
Epoch: 23, Loss: 0.009999709203839302
Epoch: 24, Loss: 0.009999727830290794
Epoch: 25, Loss: 0.009999718517065048
Epoch: 26, Loss: 0.009999707341194153
Epoch: 27, Loss: 0.009999699890613556
Epoch: 28, Loss: 0.009999710135161877
Epoch: 29, Loss: 0.009999699890613556
Epoch: 30, Loss: 0.0099997129291296
Epoch: 31, Loss: 0.0099997129291296
Epoch: 32, Loss: 0.009999696165323257
Epoch: 33, Loss: 0.00999970268458128
Epoch: 34, Loss: 0.00999970268458128
Epoch: 35, Loss: 0.00999969057738781
Epoch: 36, Loss: 0.009999695234000683
Epoch: 37, Loss: 0.009999695234000683
Epoch: 38, Loss: 0.00999968871474266
Epoch: 39, Loss: 0.009999697096645832
Epoch: 40, Loss: 0.009999692440032959
Epoch: 41, Loss: 0.00999966450035572
Epoch: 42, Loss: 0.009999680332839489
Epoch: 43, Loss: 0.009999683126807213
Epoch: 44, Loss: 0.009999672882258892
Epoch: 45, Loss: 0.009999685920774937
Epoch: 46, Loss: 0.009999683126807213
Epoch: 47, Loss: 0.009999657049775124
Epoch: 48, Loss: 0.009999662637710571
Epoch: 49, Loss: 0.009999668225646019
Epoch: 50, Loss: 0.009999663569033146
Epoch: 51, Loss: 0.009999672882258892
Epoch: 52, Loss: 0.009999655187129974
Epoch: 53, Loss: 0.009999662637710571
Epoch: 54, Loss: 0.009999655187129974
Epoch: 55, Loss: 0.009999650530517101
Epoch: 56, Loss: 0.009999657981097698
Epoch: 57, Loss: 0.009999650530517101
Epoch: 58, Loss: 0.009999645873904228
Epoch: 59, Loss: 0.009999634698033333
Epoch: 60, Loss: 0.009999648667871952
Epoch: 61, Loss: 0.009999647736549377
Epoch: 62, Loss: 0.009999631904065609
Epoch: 63, Loss: 0.009999639354646206
Epoch: 64, Loss: 0.00999964028596878
Epoch: 65, Loss: 0.009999639354646206
Epoch: 66, Loss: 0.009999632835388184
Epoch: 67, Loss: 0.00999964028596878
Epoch: 68, Loss: 0.00999962817877531
Epoch: 69, Loss: 0.00999962817877531
Epoch: 70, Loss: 0.009999623522162437
Epoch: 71, Loss: 0.009999620728194714
Epoch: 72, Loss: 0.009999620728194714
Epoch: 73, Loss: 0.009999619796872139
Epoch: 74, Loss: 0.009999602101743221
Epoch: 75, Loss: 0.009999625384807587
Epoch: 76, Loss: 0.00999961607158184
Epoch: 77, Loss: 0.009999614208936691
Epoch: 78, Loss: 0.00999961607158184
Epoch: 79, Loss: 0.009999608621001244
Epoch: 80, Loss: 0.009999608621001244
Epoch: 81, Loss: 0.009999600239098072
Epoch: 82, Loss: 0.00999961793422699
Epoch: 83, Loss: 0.009999603033065796
Epoch: 84, Loss: 0.009999602101743221
Epoch: 85, Loss: 0.009999594651162624
Epoch: 86, Loss: 0.009999576956033707
Epoch: 87, Loss: 0.009999587200582027
Epoch: 88, Loss: 0.009999590925872326
Epoch: 89, Loss: 0.00999959371984005
Epoch: 90, Loss: 0.009999590925872326
Epoch: 91, Loss: 0.009999576024711132
Epoch: 92, Loss: 0.009999574162065983
Epoch: 93, Loss: 0.009999576024711132
Epoch: 94, Loss: 0.009999584406614304
Epoch: 95, Loss: 0.00999957975000143
Epoch: 96, Loss: 0.009999565780162811
Epoch: 97, Loss: 0.009999578818678856
Epoch: 98, Loss: 0.00999956764280796
Epoch: 99, Loss: 0.009999560192227364
Epoch: 100, Loss: 0.009999563917517662
Epoch: 101, Loss: 0.009999565780162811
Epoch: 102, Loss: 0.00999955553561449
Epoch: 103, Loss: 0.009999550879001617
Epoch: 104, Loss: 0.00999955739825964
Epoch: 105, Loss: 0.009999552741646767
Epoch: 106, Loss: 0.009999551810324192
Epoch: 107, Loss: 0.009999542497098446
Epoch: 108, Loss: 0.009999550879001617
Epoch: 109, Loss: 0.00999955553561449
Epoch: 110, Loss: 0.009999539703130722
Epoch: 111, Loss: 0.009999537840485573
Epoch: 112, Loss: 0.009999540634453297
Epoch: 113, Loss: 0.009999535977840424
Epoch: 114, Loss: 0.009999532252550125
Epoch: 115, Loss: 0.009999535977840424
Epoch: 116, Loss: 0.009999530389904976
Epoch: 117, Loss: 0.009999525733292103
Epoch: 118, Loss: 0.009999532252550125
Epoch: 119, Loss: 0.009999525733292103
Epoch: 120, Loss: 0.009999524801969528
Epoch: 121, Loss: 0.009999530389904976
Epoch: 122, Loss: 0.009999523870646954
Epoch: 123, Loss: 0.00999952107667923
Epoch: 124, Loss: 0.009999505244195461
Epoch: 125, Loss: 0.009999492205679417
Epoch: 126, Loss: 0.009999493137001991
Epoch: 127, Loss: 0.009999513626098633
Epoch: 128, Loss: 0.009999497793614864
Epoch: 129, Loss: 0.009999502450227737
Epoch: 130, Loss: 0.009999504312872887
Epoch: 131, Loss: 0.009999488480389118
Epoch: 132, Loss: 0.009999473579227924
Epoch: 133, Loss: 0.009999499656260014
Epoch: 134, Loss: 0.009999481961131096
Epoch: 135, Loss: 0.009999481961131096
Epoch: 136, Loss: 0.009999486617743969
Epoch: 137, Loss: 0.009999473579227924
Epoch: 138, Loss: 0.009999465197324753
Epoch: 139, Loss: 0.009999485686421394
Epoch: 140, Loss: 0.009999467991292477
Epoch: 141, Loss: 0.009999486617743969
Epoch: 142, Loss: 0.0099994707852602
Epoch: 143, Loss: 0.009999455884099007
Epoch: 144, Loss: 0.009999471716582775
Epoch: 145, Loss: 0.009999464266002178
Epoch: 146, Loss: 0.009999459609389305
Epoch: 147, Loss: 0.00999944843351841
Epoch: 148, Loss: 0.009999461472034454
Epoch: 149, Loss: 0.009999450296163559
Epoch: 150, Loss: 0.009999445639550686
Epoch: 151, Loss: 0.009999453090131283
Epoch: 152, Loss: 0.009999444708228111
Epoch: 153, Loss: 0.009999449364840984
Epoch: 154, Loss: 0.00999944843351841
Epoch: 155, Loss: 0.009999441914260387
Epoch: 156, Loss: 0.00999944843351841
Epoch: 157, Loss: 0.009999439120292664
Epoch: 158, Loss: 0.009999438188970089
Epoch: 159, Loss: 0.009999444708228111
Epoch: 160, Loss: 0.009999439120292664
Epoch: 161, Loss: 0.009999433532357216
Epoch: 162, Loss: 0.009999415837228298
Epoch: 163, Loss: 0.00999943446367979
Epoch: 164, Loss: 0.009999418631196022
Epoch: 165, Loss: 0.00999943446367979
Epoch: 166, Loss: 0.009999430738389492
Epoch: 167, Loss: 0.009999413974583149
Epoch: 168, Loss: 0.009999423287808895
Epoch: 169, Loss: 0.009999415837228298
Epoch: 170, Loss: 0.009999423287808895
Epoch: 171, Loss: 0.009999427013099194
Epoch: 172, Loss: 0.009999415837228298
Epoch: 173, Loss: 0.009999408386647701
Epoch: 174, Loss: 0.009999413043260574
Epoch: 175, Loss: 0.009999404661357403
Epoch: 176, Loss: 0.009999393485486507
Epoch: 177, Loss: 0.009999396279454231
Epoch: 178, Loss: 0.009999404661357403
Epoch: 179, Loss: 0.009999388828873634
Epoch: 180, Loss: 0.00999939814209938
Epoch: 181, Loss: 0.009999390691518784
Epoch: 182, Loss: 0.009999390691518784
Epoch: 183, Loss: 0.009999383240938187
Epoch: 184, Loss: 0.009999388828873634
Epoch: 185, Loss: 0.009999392554163933
Epoch: 186, Loss: 0.009999386966228485
Epoch: 187, Loss: 0.00999937579035759
Epoch: 188, Loss: 0.009999378584325314
Epoch: 189, Loss: 0.00999937579035759
Epoch: 190, Loss: 0.009999381378293037
Epoch: 191, Loss: 0.009999355301260948
Epoch: 192, Loss: 0.00999937392771244
Epoch: 193, Loss: 0.009999368339776993
Epoch: 194, Loss: 0.009999367408454418
Epoch: 195, Loss: 0.009999359026551247
Epoch: 196, Loss: 0.00999935157597065
Epoch: 197, Loss: 0.009999360889196396
Epoch: 198, Loss: 0.009999353438615799
Epoch: 199, Loss: 0.009999360889196396
Epoch: 200, Loss: 0.009999354369938374
Epoch: 201, Loss: 0.009999347850680351
Epoch: 202, Loss: 0.009999341331422329
Epoch: 203, Loss: 0.009999353438615799
Epoch: 204, Loss: 0.009999348782002926
Epoch: 205, Loss: 0.009999344125390053
Epoch: 206, Loss: 0.009999331086874008
Epoch: 207, Loss: 0.009999336674809456
Epoch: 208, Loss: 0.009999332018196583
Epoch: 209, Loss: 0.009999331086874008
Epoch: 210, Loss: 0.009999336674809456
Epoch: 211, Loss: 0.009999334812164307
Epoch: 212, Loss: 0.009999324567615986
Epoch: 213, Loss: 0.009999323636293411
Epoch: 214, Loss: 0.009999326430261135
Epoch: 215, Loss: 0.00999932549893856
Epoch: 216, Loss: 0.009999321773648262
Epoch: 217, Loss: 0.009999323636293411
Epoch: 218, Loss: 0.009999321773648262
Epoch: 219, Loss: 0.009999316185712814
Epoch: 220, Loss: 0.00999930128455162
Epoch: 221, Loss: 0.009999308735132217
Epoch: 222, Loss: 0.009999309666454792
Epoch: 223, Loss: 0.009999308735132217
Epoch: 224, Loss: 0.00999930314719677
Epoch: 225, Loss: 0.00999930128455162
Epoch: 226, Loss: 0.009999295696616173
Epoch: 227, Loss: 0.009999294765293598
Epoch: 228, Loss: 0.009999285452067852
Epoch: 229, Loss: 0.009999307803809643
Epoch: 230, Loss: 0.009999296627938747
Epoch: 231, Loss: 0.009999291971325874
Epoch: 232, Loss: 0.009999299421906471
Epoch: 233, Loss: 0.009999281726777554
Epoch: 234, Loss: 0.0099992910400033
Epoch: 235, Loss: 0.009999284520745277
Epoch: 236, Loss: 0.009999287314713001
Epoch: 237, Loss: 0.00999927707016468
Epoch: 238, Loss: 0.009999270550906658
Epoch: 239, Loss: 0.009999269619584084
Epoch: 240, Loss: 0.009999271482229233
Epoch: 241, Loss: 0.009999271482229233
Epoch: 242, Loss: 0.009999270550906658
Epoch: 243, Loss: 0.009999269619584084
Epoch: 244, Loss: 0.00999927707016468
Epoch: 245, Loss: 0.009999256581068039
Epoch: 246, Loss: 0.009999263100326061
Epoch: 247, Loss: 0.009999264031648636
Epoch: 248, Loss: 0.009999263100326061
Epoch: 249, Loss: 0.009999269619584084
Epoch: 250, Loss: 0.009999251924455166
Epoch: 251, Loss: 0.009999244473874569
Epoch: 252, Loss: 0.009999243542551994
Epoch: 253, Loss: 0.009999249130487442
Epoch: 254, Loss: 0.009999256581068039
Epoch: 255, Loss: 0.009999239817261696
Epoch: 256, Loss: 0.009999248199164867
Epoch: 257, Loss: 0.009999233298003674
Epoch: 258, Loss: 0.009999251924455166
Epoch: 259, Loss: 0.009999236091971397
Epoch: 260, Loss: 0.009999217465519905
Epoch: 261, Loss: 0.009999233298003674
Epoch: 262, Loss: 0.009999237023293972
Epoch: 263, Loss: 0.009999226778745651
Epoch: 264, Loss: 0.00999923050403595
Epoch: 265, Loss: 0.009999224916100502
Epoch: 266, Loss: 0.009999210946261883
Epoch: 267, Loss: 0.009999217465519905
Epoch: 268, Loss: 0.009999225847423077
Epoch: 269, Loss: 0.009999208152294159
Epoch: 270, Loss: 0.00999921839684248
Epoch: 271, Loss: 0.009999210946261883
Epoch: 272, Loss: 0.009999193251132965
Epoch: 273, Loss: 0.009999210014939308
Epoch: 274, Loss: 0.009999214671552181
Epoch: 275, Loss: 0.009999193251132965
Epoch: 276, Loss: 0.00999920442700386
Epoch: 277, Loss: 0.009999201633036137
Epoch: 278, Loss: 0.009999185800552368
Epoch: 279, Loss: 0.009999196045100689
Epoch: 280, Loss: 0.009999207220971584
Epoch: 281, Loss: 0.009999181143939495
Epoch: 282, Loss: 0.009999187663197517
Epoch: 283, Loss: 0.009999183937907219
Epoch: 284, Loss: 0.009999177418649197
Epoch: 285, Loss: 0.009999181143939495
Epoch: 286, Loss: 0.009999176487326622
Epoch: 287, Loss: 0.009999178349971771
Epoch: 288, Loss: 0.00999918207526207
Epoch: 289, Loss: 0.009999176487326622
Epoch: 290, Loss: 0.009999161586165428
Epoch: 291, Loss: 0.009999178349971771
Epoch: 292, Loss: 0.009999173693358898
Epoch: 293, Loss: 0.009999169036746025
Epoch: 294, Loss: 0.009999163448810577
Epoch: 295, Loss: 0.009999164380133152
Epoch: 296, Loss: 0.009999148547649384
Epoch: 297, Loss: 0.009999158792197704
Epoch: 298, Loss: 0.009999162517488003
Epoch: 299, Loss: 0.009999148547649384
Epoch: 300, Loss: 0.009999155066907406
Epoch: 301, Loss: 0.009999153204262257
Epoch: 302, Loss: 0.009999146685004234
Epoch: 303, Loss: 0.009999141097068787
Epoch: 304, Loss: 0.009999138303101063
Epoch: 305, Loss: 0.00999913178384304
Epoch: 306, Loss: 0.009999146685004234
Epoch: 307, Loss: 0.009999142028391361
Epoch: 308, Loss: 0.009999141097068787
Epoch: 309, Loss: 0.00999913364648819
Epoch: 310, Loss: 0.009999126195907593
Epoch: 311, Loss: 0.009999116882681847
Epoch: 312, Loss: 0.00999913178384304
Epoch: 313, Loss: 0.009999125264585018
Epoch: 314, Loss: 0.009999103844165802
Epoch: 315, Loss: 0.009999106638133526
Epoch: 316, Loss: 0.009999101981520653
Epoch: 317, Loss: 0.009999101981520653
Epoch: 318, Loss: 0.009999100118875504
Epoch: 319, Loss: 0.009999105706810951
Epoch: 320, Loss: 0.009999112226068974
Epoch: 321, Loss: 0.00999909546226263
Epoch: 322, Loss: 0.009999104775488377
Epoch: 323, Loss: 0.009999091736972332
Epoch: 324, Loss: 0.009999088011682034
Epoch: 325, Loss: 0.009999092668294907
Epoch: 326, Loss: 0.00999908335506916
Epoch: 327, Loss: 0.00999908521771431
Epoch: 328, Loss: 0.00999908335506916
Epoch: 329, Loss: 0.00999908335506916
Epoch: 330, Loss: 0.009999081492424011
Epoch: 331, Loss: 0.009999080561101437
Epoch: 332, Loss: 0.00999908335506916
Epoch: 333, Loss: 0.009999077767133713
Epoch: 334, Loss: 0.00999908335506916
Epoch: 335, Loss: 0.009999080561101437
Epoch: 336, Loss: 0.009999064728617668
Epoch: 337, Loss: 0.009999074041843414
Epoch: 338, Loss: 0.009999064728617668
Epoch: 339, Loss: 0.00999907311052084
Epoch: 340, Loss: 0.009999068453907967
Epoch: 341, Loss: 0.009999051690101624
Epoch: 342, Loss: 0.009999057278037071
Epoch: 343, Loss: 0.009999050758779049
Epoch: 344, Loss: 0.00999906100332737
Epoch: 345, Loss: 0.009999055415391922
Epoch: 346, Loss: 0.009999058209359646
Epoch: 347, Loss: 0.00999904703348875
Epoch: 348, Loss: 0.009999042376875877
Epoch: 349, Loss: 0.009999049827456474
Epoch: 350, Loss: 0.009999040514230728
Epoch: 351, Loss: 0.009999039582908154
Epoch: 352, Loss: 0.009999045170843601
Epoch: 353, Loss: 0.009999042376875877
Epoch: 354, Loss: 0.00999903492629528
Epoch: 355, Loss: 0.009999020025134087
Epoch: 356, Loss: 0.009999014437198639
Epoch: 357, Loss: 0.009999031201004982
Epoch: 358, Loss: 0.009999035857617855
Epoch: 359, Loss: 0.00999902468174696
Epoch: 360, Loss: 0.009999006986618042
Epoch: 361, Loss: 0.009999021887779236
Epoch: 362, Loss: 0.009999006986618042
Epoch: 363, Loss: 0.009999014437198639
Epoch: 364, Loss: 0.009999028407037258
Epoch: 365, Loss: 0.009999014437198639
Epoch: 366, Loss: 0.009998999536037445
Epoch: 367, Loss: 0.009999005123972893
Epoch: 368, Loss: 0.009999002330005169
Epoch: 369, Loss: 0.009999006986618042
Epoch: 370, Loss: 0.00999901071190834
Epoch: 371, Loss: 0.009998992085456848
Epoch: 372, Loss: 0.009998991154134274
Epoch: 373, Loss: 0.009998999536037445
Epoch: 374, Loss: 0.009998990222811699
Epoch: 375, Loss: 0.009998987428843975
Epoch: 376, Loss: 0.009998995810747147
Epoch: 377, Loss: 0.009998984634876251
Epoch: 378, Loss: 0.009998984634876251
Epoch: 379, Loss: 0.009998987428843975
Epoch: 380, Loss: 0.009998977184295654
Epoch: 381, Loss: 0.009998979046940804
Epoch: 382, Loss: 0.009998984634876251
Epoch: 383, Loss: 0.009998977184295654
Epoch: 384, Loss: 0.009998987428843975
Epoch: 385, Loss: 0.009998971596360207
Epoch: 386, Loss: 0.009998965077102184
Epoch: 387, Loss: 0.00999896228313446
Epoch: 388, Loss: 0.009998967871069908
Epoch: 389, Loss: 0.009998952969908714
Epoch: 390, Loss: 0.009998960420489311
Epoch: 391, Loss: 0.009998965077102184
Epoch: 392, Loss: 0.009998953901231289
Epoch: 393, Loss: 0.009998946450650692
Epoch: 394, Loss: 0.009998952969908714
Epoch: 395, Loss: 0.009998946450650692
Epoch: 396, Loss: 0.009998956695199013
Epoch: 397, Loss: 0.009998957626521587
Epoch: 398, Loss: 0.009998953901231289
Epoch: 399, Loss: 0.009998947381973267
Epoch: 400, Loss: 0.009998932480812073
Epoch: 401, Loss: 0.009998925030231476
Epoch: 402, Loss: 0.009998935274779797
Epoch: 403, Loss: 0.00999893993139267
Epoch: 404, Loss: 0.009998922236263752
Epoch: 405, Loss: 0.009998930618166924
Epoch: 406, Loss: 0.009998930618166924
Epoch: 407, Loss: 0.009998919442296028
Epoch: 408, Loss: 0.009998932480812073
Epoch: 409, Loss: 0.009998925030231476
Epoch: 410, Loss: 0.009998925030231476
Epoch: 411, Loss: 0.009998921304941177
Epoch: 412, Loss: 0.009998920373618603
Epoch: 413, Loss: 0.009998925030231476
Epoch: 414, Loss: 0.009998917579650879
Epoch: 415, Loss: 0.009998910129070282
Epoch: 416, Loss: 0.009998908266425133
Epoch: 417, Loss: 0.009998912923038006
Epoch: 418, Loss: 0.009998912923038006
Epoch: 419, Loss: 0.009998894296586514
Epoch: 420, Loss: 0.009998898021876812
Epoch: 421, Loss: 0.009998908266425133
Epoch: 422, Loss: 0.009998902678489685
Epoch: 423, Loss: 0.009998898953199387
Epoch: 424, Loss: 0.009998894296586514
Epoch: 425, Loss: 0.009998893365263939
Epoch: 426, Loss: 0.009998884052038193
Epoch: 427, Loss: 0.009998900815844536
Epoch: 428, Loss: 0.009998895227909088
Epoch: 429, Loss: 0.009998884052038193
Epoch: 430, Loss: 0.009998881258070469
Epoch: 431, Loss: 0.009998868219554424
Epoch: 432, Loss: 0.009998872876167297
Epoch: 433, Loss: 0.009998871944844723
Epoch: 434, Loss: 0.009998875670135021
Epoch: 435, Loss: 0.009998874738812447
Epoch: 436, Loss: 0.009998869150876999
Epoch: 437, Loss: 0.00999886728823185
Epoch: 438, Loss: 0.009998868219554424
Epoch: 439, Loss: 0.009998857043683529
Epoch: 440, Loss: 0.009998861700296402
Epoch: 441, Loss: 0.009998863562941551
Epoch: 442, Loss: 0.009998860768973827
Epoch: 443, Loss: 0.00999885518103838
Epoch: 444, Loss: 0.009998844936490059
Epoch: 445, Loss: 0.009998844936490059
Epoch: 446, Loss: 0.009998850524425507
Epoch: 447, Loss: 0.009998849593102932
Epoch: 448, Loss: 0.00999884307384491
Epoch: 449, Loss: 0.009998839348554611
Epoch: 450, Loss: 0.009998834691941738
Epoch: 451, Loss: 0.009998833760619164
Epoch: 452, Loss: 0.009998837485909462
Epoch: 453, Loss: 0.00999883096665144
Epoch: 454, Loss: 0.009998830035328865
Epoch: 455, Loss: 0.009998830035328865
Epoch: 456, Loss: 0.009998831897974014
Epoch: 457, Loss: 0.009998831897974014
Epoch: 458, Loss: 0.00999881885945797
Epoch: 459, Loss: 0.009998819790780544
Epoch: 460, Loss: 0.00999881885945797
Epoch: 461, Loss: 0.009998822584748268
Epoch: 462, Loss: 0.00999881699681282
Epoch: 463, Loss: 0.009998811408877373
Epoch: 464, Loss: 0.009998807683587074
Epoch: 465, Loss: 0.009998802095651627
Epoch: 466, Loss: 0.009998812340199947
Epoch: 467, Loss: 0.00999880488961935
Epoch: 468, Loss: 0.00999880488961935
Epoch: 469, Loss: 0.009998809546232224
Epoch: 470, Loss: 0.00999879464507103
Epoch: 471, Loss: 0.00999879464507103
Epoch: 472, Loss: 0.009998815134167671
Epoch: 473, Loss: 0.009998789057135582
Epoch: 474, Loss: 0.009998801164329052
Epoch: 475, Loss: 0.009998783469200134
Epoch: 476, Loss: 0.00999878253787756
Epoch: 477, Loss: 0.009998777881264687
Epoch: 478, Loss: 0.009998775087296963
Epoch: 479, Loss: 0.009998779743909836
Epoch: 480, Loss: 0.009998779743909836
Epoch: 481, Loss: 0.00999878253787756
Epoch: 482, Loss: 0.009998769499361515
Epoch: 483, Loss: 0.009998762980103493
Epoch: 484, Loss: 0.009998767636716366
Epoch: 485, Loss: 0.009998775087296963
Epoch: 486, Loss: 0.009998777881264687
Epoch: 487, Loss: 0.009998767636716366
Epoch: 488, Loss: 0.00999875646084547
Epoch: 489, Loss: 0.009998766705393791
Epoch: 490, Loss: 0.009998752735555172
Epoch: 491, Loss: 0.009998757392168045
Epoch: 492, Loss: 0.009998755529522896
Epoch: 493, Loss: 0.009998757392168045
Epoch: 494, Loss: 0.009998752735555172
Epoch: 495, Loss: 0.009998748078942299
Epoch: 496, Loss: 0.00999875646084547
Epoch: 497, Loss: 0.009998736903071404
Epoch: 498, Loss: 0.009998749941587448
Epoch: 499, Loss: 0.009998749941587448
Epoch: 500, Loss: 0.009998742491006851
Epoch: 501, Loss: 0.009998742491006851
Epoch: 502, Loss: 0.009998735040426254
Epoch: 503, Loss: 0.00999872200191021
Epoch: 504, Loss: 0.009998742491006851
Epoch: 505, Loss: 0.009998737834393978
Epoch: 506, Loss: 0.009998712688684464
Epoch: 507, Loss: 0.009998710826039314
Epoch: 508, Loss: 0.009998714551329613
Epoch: 509, Loss: 0.009998701512813568
Epoch: 510, Loss: 0.009998705238103867
Epoch: 511, Loss: 0.00999872200191021
Epoch: 512, Loss: 0.009998705238103867
Epoch: 513, Loss: 0.009998715482652187
Epoch: 514, Loss: 0.00999869778752327
Epoch: 515, Loss: 0.009998693130910397
Epoch: 516, Loss: 0.00999869778752327

KeyboardInterrupt:

In [78]:
## Train accuracy 

with torch.no_grad():

    # Predictions
    y_pred = model(X_train)

    # Convert probabilities to 0 or 1
    predicted = (y_pred >= 0.5).float()

    # Accuracy
    accuracy = (predicted == y_train).float().mean()

    print(f"Train Accuracy: {accuracy.item() * 100:.2f}%")

## Test accuracy 

with torch.no_grad():

    # Predictions
    y_pred = model(X_test)

    # Convert probabilities to 0 or 1
    predicted = (y_pred >= 0.5).float()

    # Accuracy
    accuracy = (predicted == y_test).float().mean()

    print(f"Test Accuracy: {accuracy.item() * 100:.2f}%")

Train Accuracy: 100.00%
Test Accuracy: 75.00%

In [81]:
from sklearn.metrics import confusion_matrix, classification_report

with torch.no_grad():

    # Predictions
    y_pred = model(X_test)

    # Convert probabilities -> 0 or 1
    predicted = (y_pred >= 0.5).float()

    # Convert tensors -> numpy
    cm = confusion_matrix(
        y_test.cpu().numpy(),
        predicted.cpu().numpy()
    )
    
    print(classification_report(
        y_test.cpu().numpy(),
        predicted.cpu().numpy()
    ))

    print(cm)

              precision    recall  f1-score   support

         0.0       0.50      1.00      0.67         1
         1.0       1.00      0.67      0.80         3

    accuracy                           0.75         4
   macro avg       0.75      0.83      0.73         4
weighted avg       0.88      0.75      0.77         4

[[1 0]
 [1 2]]